In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


In [20]:
import warnings
warnings.filterwarnings('ignore')
df =pd.read_csv('sonar_dataset.csv',header =None)
df.sample(5)

0       1       2       3       4       5       6       7       8   \
90   0.0126  0.0519  0.0621  0.0518  0.1072  0.2587  0.2304  0.2067  0.3416   
95   0.0291  0.0400  0.0771  0.0809  0.0521  0.1051  0.0145  0.0674  0.1294   
117  0.0228  0.0106  0.0130  0.0842  0.1117  0.1506  0.1776  0.0997  0.1428   
118  0.0363  0.0478  0.0298  0.0210  0.1409  0.1916  0.1349  0.1613  0.1703   
28   0.0100  0.0275  0.0190  0.0371  0.0416  0.0201  0.0314  0.0651  0.1896   

         9   ...      51      52      53      54      55      56      57  \
90   0.4284  ...  0.0208  0.0048  0.0199  0.0126  0.0022  0.0037  0.0034   
95   0.1146  ...  0.0056  0.0237  0.0204  0.0050  0.0137  0.0164  0.0081   
117  0.2227  ...  0.0098  0.0178  0.0077  0.0074  0.0095  0.0055  0.0045   
118  0.1444  ...  0.0115  0.0190  0.0055  0.0096  0.0050  0.0066  0.0114   
28   0.2668  ...  0.0088  0.0104  0.0036  0.0088  0.0047  0.0117  0.0020   

         58      59  60  
90   0.0114  0.0077   R  
95   0.0139  0.0111   R  
117  0.0063  0.0039   M  
118  0.0073  0.0033   M  
28   0.0091  0.0058   R  

[5 rows x 61 columns]

In [21]:
df.shape

(208, 61)

In [18]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [23]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [27]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [30]:
X = df.drop(60,axis=1)
y = df[60]

In [32]:
y = pd.get_dummies(y,drop_first = True)
y.sample(5)         

R
144  0
102  0
51   1
15   1
48   1

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test  =train_test_split(X,y,test_size=0.25,random_state = 1)

In [38]:
X_train.shape

(156, 60)

In [36]:
import tensorflow as tf
from tensorflow import keras

In [44]:
model=keras.Sequential([
    keras.layers.Dense(60,input_dim = 60,activation ='relu'),
    keras.layers.Dense(30,input_dim = 60,activation ='relu'),
    keras.layers.Dense(15,input_dim = 60,activation ='relu'),
    keras.layers.Dense(1,activation = 'sigmoid')
])

model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics =['accuracy'])

model.fit(X_train,y_train,epochs =100,batch_size =8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.6819 - accuracy: 0.5705
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6538 - accuracy: 0.6859
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6319 - accuracy: 0.6923
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6014 - accuracy: 0.6987
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5734 - accuracy: 0.7564
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5469 - accuracy: 0.7949
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5000 - accuracy: 0.7949
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4647 - accuracy: 0.8077
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4288 - accuracy: 0.8526
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4063 - accuracy: 0.8590
Epoch 11/

20/20 [==============================] - 0s 2ms/step - loss: 0.0047 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0041 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0031 - accuracy: 1.0000
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0031 - accuracy: 1.0000
Epoch 93/100


In [46]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.8784 - accuracy: 0.7692


[0.8784254789352417, 0.7692307829856873]

In [56]:
y_p = model.predict(X_test).reshape(-1)
print(y_p[:5])
y_p = np.round(y_p)
y_p[:5]

[2.1360453e-09 9.5844615e-01 2.0245954e-01 1.6408952e-06 9.9999690e-01]


array([0., 1., 0., 0., 1.], dtype=float32)

In [58]:
y_test[:5]

R
186  0
155  0
165  0
200  0
58   1

In [60]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,y_p))

              precision    recall  f1-score   support

           0       0.71      0.93      0.81        27
           1       0.88      0.60      0.71        25

    accuracy                           0.77        52
   macro avg       0.80      0.76      0.76        52
weighted avg       0.80      0.77      0.76        52



In [63]:
modeld=keras.Sequential([
    keras.layers.Dense(60,input_dim = 60,activation ='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30,input_dim = 60,activation ='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15,input_dim = 60,activation ='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation = 'sigmoid')
])

modeld.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics =['accuracy'])

modeld.fit(X_train,y_train,epochs =100,batch_size =8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7385 - accuracy: 0.4423
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7453 - accuracy: 0.4167
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7221 - accuracy: 0.5321
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7074 - accuracy: 0.4551
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7092 - accuracy: 0.5128
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6986 - accuracy: 0.4936
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6887 - accuracy: 0.5449
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6821 - accuracy: 0.5641
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6915 - accuracy: 0.5449
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6746 - accuracy: 0.6346
Epoch 11/

20/20 [==============================] - 0s 2ms/step - loss: 0.3107 - accuracy: 0.9167
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3729 - accuracy: 0.8462
Epoch 85/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2733 - accuracy: 0.9231
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3176 - accuracy: 0.8782
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2980 - accuracy: 0.8910
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2941 - accuracy: 0.8974
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3602 - accuracy: 0.8590
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3394 - accuracy: 0.8590
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3365 - accuracy: 0.8654
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3014 - accuracy: 0.9103
Epoch 93/100


In [67]:
modeld.evaluate(X_test,y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.5403 - accuracy: 0.7885


[0.5403127670288086, 0.7884615659713745]

In [68]:
y_p = modeld.predict(X_test).reshape(-1)
y_p = np.round(y_p)
y_p[:5]

array([0., 1., 1., 0., 1.], dtype=float32)

In [69]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,y_p))

              precision    recall  f1-score   support

           0       0.77      0.85      0.81        27
           1       0.82      0.72      0.77        25

    accuracy                           0.79        52
   macro avg       0.79      0.79      0.79        52
weighted avg       0.79      0.79      0.79        52

