In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot("amazing restaurant",30)

[11, 9]

In [41]:
vocab_size = 30
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[5, 14],
 [11, 9],
 [24, 25],
 [16, 9, 15],
 [7, 4, 5],
 [28, 14],
 [20, 4, 13],
 [29, 7],
 [29, 19],
 [4, 29]]

In [42]:
max_length = 3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding = 'post') 
print(padded_reviews)

[[ 5 14  0]
 [11  9  0]
 [24 25  0]
 [16  9 15]
 [ 7  4  5]
 [28 14  0]
 [20  4 13]
 [29  7  0]
 [29 19  0]
 [ 4 29  0]]


In [43]:
embeded_vector_size = 4
model=Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name = 'embedding'))
model.add(Flatten())
model.add(Dense(1,activation = 'sigmoid'))

In [44]:
X = padded_reviews
y = sentiment

In [45]:
model.compile(optimizer='adam',loss = 'binary_crossentropy',metrics =['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              120       
_________________________________________________________________
flatten_4 (Flatten)          (None, 12)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 13        
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [46]:
model.fit(X,y,epochs = 5,verbose = 0)

In [47]:
model.evaluate(X,y)

1/1 [==============================] - 0s 223ms/step - loss: 0.6798 - accuracy: 0.8000


[0.6798497438430786, 0.800000011920929]

In [48]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [49]:
weights[5]

array([ 0.01271981, -0.04549135,  0.04318393,  0.01229899], dtype=float32)

In [50]:
weights[11]

array([-0.0169175 ,  0.05055955, -0.02303255,  0.01714278], dtype=float32)